service: api
runtime: nodejs20
env: standard

# Automatically scale based on load
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10
  min_pending_latency: automatic
  max_pending_latency: automatic

env_variables:
  NODE_ENV: production
  LOG_LEVEL: info
  ALLOWED_ORIGIN: https://evalgpt.com
  EVALPRD_MODEL: gpt-5
  # OPENAI_API_KEY - WARNING: Use Secret Manager in production, not hardcoded here
  OPENAI_API_KEY: [REDACTED]

handlers:
  # Let the Node server handle all routes
  - url: /.*
    script: auto
    secure: always
