service: api
env: flex
runtime: custom

env_variables:
  NODE_ENV: production
  LOG_LEVEL: info
  # Set this to your domain when mapped (not used for same-origin requests via dispatch)
  ALLOWED_ORIGIN: https://evalgpt.com
  EVALPRD_MODEL: gpt-4o
  # OPENAI_API_KEY should be set via 'gcloud app deploy --set-env-vars' or Secret Manager

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

network:
  forwarded_ports:
    - 8080
