// Spotify PRD evaluation data loader
// Uses static data generated from real API calls (see scripts/generate-spotify-results.mjs)

import type {
  BinaryScoreOutput,
  FixPlanOutput,
  AgentTasksOutput,
} from "../types/api";
import {
  spotifyBinaryScore,
  spotifyFixPlan,
  spotifyAgentTasks,
} from "../data/spotifyResults";

export interface SpotifyEvaluationData {
  binaryScore: BinaryScoreOutput;
  fixPlan: FixPlanOutput;
  agentTasks: AgentTasksOutput;
}

/**
 * Load Spotify PRD evaluation results from static data
 * Data is generated by running: node frontend/scripts/generate-spotify-results.mjs
 */
export async function loadSpotifyData(): Promise<SpotifyEvaluationData> {
  // Return static data immediately (no API calls)
  return {
    binaryScore: spotifyBinaryScore,
    fixPlan: spotifyFixPlan,
    agentTasks: spotifyAgentTasks,
  };
}

